version: "3"
services:
  db:
    image: postgres
    container_name: clipbot-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: clipbot
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "admin"]
      timeout: 10s
      retries: 5
    volumes:
      - db:/var/lib/postgresql/data

volumes:
    db:
      driver: local
