// Code generated by mockery v2.20.0. DO NOT EDIT.

package queue

import mock "github.com/stretchr/testify/mock"

// ProducerMocked is an autogenerated mock type for the IProducer type
type ProducerMocked struct {
	mock.Mock
}

// Produce provides a mock function with given fields: topic, data
func (_m *ProducerMocked) Produce(topic string, data []byte) error {
	ret := _m.Called(topic, data)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, []byte) error); ok {
		r0 = rf(topic, data)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// Stop provides a mock function with given fields:
func (_m *ProducerMocked) Stop() {
	_m.Called()
}

type mockConstructorTestingTNewProducerMocked interface {
	mock.TestingT
	Cleanup(func())
}

// NewProducerMocked creates a new instance of ProducerMocked. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewProducerMocked(t mockConstructorTestingTNewProducerMocked) *ProducerMocked {
	mock := &ProducerMocked{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
